[env:dfrobot_firebeetle2_esp32e]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = dfrobot_firebeetle2_esp32e
framework = arduino
monitor_speed = 115200
lib_deps =
    mikalhart/TinyGPSPlus
    bblanchon/ArduinoJson
